# Generated by Django 6.1 on 2026-08-13 20:32

import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('user_agent', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-last_activity_at',),
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('public_key', models.CharField(default=chat.models.generate_public_key, editable=False, max_length=32, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('feedback', models.CharField(blank=True, choices=[('helpful', 'Helpful'), ('not_helpful', 'Not helpful')], max_length=20)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chat.site'),
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('widget_loaded', 'Widget loaded'), ('conversation_started', 'Conversation started'), ('user_message', 'User message'), ('assistant_answered', 'Assistant answered'), ('answer_helpful', 'Answer helpful'), ('answer_not_helpful', 'Answer not helpful'), ('human_requested', 'Human requested'), ('ticket_created', 'Ticket created'), ('fallback_triggered', 'Fallback triggered'), ('conversation_archived', 'Conversation archived')], max_length=40)),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='chat.conversation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='chat.site')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='دستیار هوش مصنوعی', max_length=120)),
                ('subtitle', models.CharField(default='پاسخ\u200cهای فوری به سوالات شما', max_length=200)),
                ('greeting', models.TextField(default='سلام! 👋 چطور می\u200cتوانم کمکتان کنم؟')),
                ('primary_color', models.CharField(default='#5048E5', max_length=20)),
                ('secondary_color', models.CharField(default='#7C3AED', max_length=20)),
                ('font_family', models.CharField(default='Inter, ui-sans-serif, system-ui, sans-serif', max_length=120)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom right'), ('bottom-left', 'Bottom left')], default='bottom-right', max_length=20)),
                ('show_history', models.BooleanField(default=True)),
                ('allow_feedback', models.BooleanField(default=True)),
                ('show_powered_by', models.BooleanField(default=True)),
                ('suggestions', models.JSONField(blank=True, default=list)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.6, max_digits=3)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('system_prompt', models.TextField(blank=True)),
                ('user_prompt', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget_config', to='chat.site')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('site', 'external_id'), name='unique_conversation_per_site'),
        ),
    ]
