# Generated by Django 6.1 on 2026-08-13 22:02

from django.db import migrations, models


def migrate_to_single_site(apps, schema_editor):
    WidgetConfig = apps.get_model("chat", "WidgetConfig")
    Conversation = apps.get_model("chat", "Conversation")

    configs = list(WidgetConfig.objects.select_related("site").order_by("-id"))
    if configs:
        # Keep the latest configuration. This preserves the current customer's
        # settings when the old local database contains demo data as well.
        primary = configs[0]
        site = primary.site
        primary.business_name = site.name or primary.business_name
        if site.domain:
            domain = site.domain.strip()
            if not domain.startswith(("http://", "https://")):
                domain = ("http://" if domain in {"localhost", "127.0.0.1"} else "https://") + domain
            primary.website_url = domain
        primary.save(
            update_fields=("business_name", "website_url"),
        )
        WidgetConfig.objects.exclude(pk=primary.pk).delete()

    seen = set()
    for conversation in Conversation.objects.order_by("id"):
        external_id = conversation.external_id
        if external_id in seen:
            conversation.external_id = f"{external_id[:88]}-{conversation.pk}"
            conversation.save(update_fields=("external_id",))
        seen.add(conversation.external_id)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='business_name',
            field=models.CharField(default='AI Support', max_length=200),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='faq_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='privacy_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='support_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='website_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.RunPython(migrate_to_single_site, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='widgetconfig',
            name='site',
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='site',
        ),
        migrations.AlterModelOptions(
            name='analyticsevent',
            options={'ordering': ('-created_at',), 'verbose_name': 'Analytics event', 'verbose_name_plural': 'Analytics events'},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-last_activity_at',), 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterModelOptions(
            name='widgetconfig',
            options={'verbose_name': 'Widget settings', 'verbose_name_plural': 'Widget settings'},
        ),
        migrations.RemoveConstraint(
            model_name='conversation',
            name='unique_conversation_per_site',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='external_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='site',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='singleton_key',
            field=models.PositiveSmallIntegerField(default=1, editable=False, unique=True),
        ),
    ]
