# Generated by Django 6.1 on 2026-08-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_widgetconfig_site_remove_analyticsevent_site_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('txt', 'Text'), ('docx', 'Word')], max_length=10)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('embedding_count', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Knowledge document',
                'verbose_name_plural': 'Knowledge documents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='border_radius',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='bot_avatar_text',
            field=models.CharField(default='AI', max_length=8),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='header_badge',
            field=models.CharField(default='ONLINE', max_length=40),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='input_placeholder',
            field=models.CharField(default='سؤال خود را بنویسید...', max_length=120),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='mobile_fullscreen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='panel_height',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='panel_width',
            field=models.PositiveIntegerField(default=380),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='theme_mode',
            field=models.CharField(choices=[('gradient', 'Gradient'), ('solid', 'Solid'), ('glass', 'Glass')], default='gradient', max_length=20),
        ),
    ]
