# Generated by Django 6.1 on 2026-08-17

from django.db import migrations, models

import chat.encrypted_fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_document_widgetconfig_border_radius_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('llm_api_key', chat.encrypted_fields.EncryptedCharField(blank=True, max_length=1024)),
                ('llm_base_url', models.CharField(blank=True, max_length=500)),
                ('llm_model', models.CharField(blank=True, max_length=120)),
                ('llm_max_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('llm_max_retries', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding_api_key', chat.encrypted_fields.EncryptedCharField(blank=True, max_length=1024)),
                ('embedding_base_url', models.CharField(blank=True, max_length=500)),
                ('embedding_model', models.CharField(blank=True, max_length=120)),
                ('embedding_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('embedding_max_retries', models.PositiveIntegerField(blank=True, null=True)),
                ('rag_max_concurrent', models.PositiveIntegerField(blank=True, null=True)),
                ('response_cache_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI provider settings',
                'verbose_name_plural': 'AI provider settings',
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'created_at'], name='evt_type_created_idx'),
        ),
    ]
