# Generated by Django 6.1 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_providersettings_message_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='providersettings',
            name='widget_allowed_origins',
            field=models.TextField(blank=True, help_text='One origin per line, e.g. https://example.com'),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='widget_public_key',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
