# Generated by Django 6.1 on 2026-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_providersettings_widget_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='analyticsevent',
            name='conversation',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='msg_conv_created_idx',
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('widget_loaded', 'Widget loaded'), ('user_message', 'User message'), ('assistant_answered', 'Assistant answered'), ('answer_helpful', 'Answer helpful'), ('answer_not_helpful', 'Answer not helpful'), ('fallback_triggered', 'Fallback triggered'), ('error_occurred', 'Error occurred'), ('high_pressure', 'High pressure detected')], max_length=40),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='show_history',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
