# Generated by Django 6.1 on 2026-09-02 17:10

import chat.encrypted_fields
import chat.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_widget_position_icon_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(db_index=True, default=chat.models.generate_conversation_id, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('handed_off', 'Handed off')], default='open', max_length=20)),
                ('first_intent', models.CharField(blank=True, max_length=40)),
                ('last_intent', models.CharField(blank=True, max_length=40)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('origin', models.CharField(blank=True, max_length=300)),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('visitor_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='CrawlJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_url', models.URLField(max_length=1000)),
                ('max_pages', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('pages_found', models.PositiveIntegerField(default=0)),
                ('pages_indexed', models.PositiveIntegerField(default=0)),
                ('pages_failed', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crawl job',
                'verbose_name_plural': 'Crawl jobs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Upload'), ('crawl', 'Crawl')], default='upload', max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='telegram_bot_token',
            field=chat.encrypted_fields.EncryptedCharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='providersettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='context_window',
            field=models.PositiveSmallIntegerField(default=6, help_text='How many previous messages are included as conversation context (0-20).'),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='enable_handoff',
            field=models.BooleanField(default=True, help_text='Offer human handoff when the assistant cannot resolve an issue.'),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='enable_lead_capture',
            field=models.BooleanField(default=True, help_text='Offer an in-widget lead form (email/telegram/whatsapp handoff UIs use it too).'),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='enable_streaming',
            field=models.BooleanField(default=True, help_text='Stream AI answers token-by-token (SSE) with automatic fallback.'),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='handoff_contact_url',
            field=models.URLField(blank=True, help_text='Site contact form URL', max_length=500),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='handoff_email',
            field=models.EmailField(blank=True, help_text='Fallback email for handoff/lead notifications.', max_length=254),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='handoff_message',
            field=models.TextField(default='پاسخ این سؤال در دانش دستیار نبود؛ یک کارشناس انسانی بررسی می\u200cکند.'),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='handoff_telegram_url',
            field=models.URLField(blank=True, help_text='e.g. https://t.me/yourteam', max_length=500),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='handoff_trigger',
            field=models.CharField(choices=[('always', 'Always show handoff option'), ('low_confidence', 'Only on low-confidence / fallback answers'), ('off', 'Never (disable handoff UI)')], default='low_confidence', max_length=20),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='handoff_whatsapp_url',
            field=models.URLField(blank=True, help_text='e.g. https://wa.me/98912...', max_length=500),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='lead_form_description',
            field=models.CharField(default='کارشناس ما در اسرع وقت با شما تماس می\u200cگیرد.', max_length=400),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='lead_form_title',
            field=models.CharField(default='برای پیگیری، راه تماس بگذارید', max_length=200),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='show_citations',
            field=models.BooleanField(default=True, help_text='Show source chips (document titles / page links) under AI answers.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='HandoffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('contact_form', 'Site contact form')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], default='new', max_length=20)),
                ('question', models.TextField(blank=True, help_text="The visitor's last question that triggered handoff.")),
                ('notified', models.BooleanField(default=False)),
                ('origin', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handoff_requests', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Handoff request',
                'verbose_name_plural': 'Handoff requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('source', models.CharField(choices=[('widget_form', 'Widget form'), ('handoff_email', 'Handoff — email'), ('handoff_telegram', 'Handoff — Telegram'), ('handoff_whatsapp', 'Handoff — WhatsApp'), ('handoff_contact', 'Handoff — contact form')], default='widget_form', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=300)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='chat.lead'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=40)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('used_fallback', models.BooleanField(default=False)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_streamed', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpful', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.message')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='UnansweredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=2000)),
                ('question_hash', models.CharField(db_index=True, max_length=64)),
                ('count', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('no_context', 'No matching context'), ('low_confidence', 'Low-confidence answer'), ('model_fallback', 'Model declared it does not know')], default='low_confidence', max_length=20)),
                ('last_intent', models.CharField(blank=True, max_length=40)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unanswered_questions', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Unanswered question',
                'verbose_name_plural': 'Unanswered questions',
                'ordering': ('-count', '-updated_at'),
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='msg_conv_created_idx'),
        ),
    ]
