# Generated by Django 5.2.13 on 2026-09-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_prompt_builder_business_rules_crawl_multi'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='enable_conversation_memory',
            field=models.BooleanField(default=True, help_text='When disabled, the model gets no history (each turn stateless). When enabled, context_window controls how much history.'),
        ),
        migrations.AlterField(
            model_name='widgetconfig',
            name='context_window',
            field=models.PositiveSmallIntegerField(default=6, help_text='How many previous messages are included as conversation context (0-20). Ignored when memory is disabled.'),
        ),
    ]
