# Generated by Django 5.2.13 on 2026-09-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_widgetconfig_enable_conversation_memory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetconfig',
            name='widget_theme',
            field=models.CharField(choices=[('classic', 'کلاسیک — سبک و پایدار'), ('onyx', 'حرفه\u200cای (Onyx) — تیره و پرمیوم'), ('linen', 'مدرن (Linen) — روشن و مینیمال')], default='classic', help_text='نسخه\u200cی رابط کاربری ویجت. هر سه از یک تنظیمات شخصی\u200cسازی استفاده می\u200cکنند.', max_length=20),
        ),
    ]
