# Generated by Django 5.2.13 on 2026-09-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_widgetconfig_widget_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widgetconfig',
            name='widget_theme',
            field=models.CharField(choices=[('classic', 'کلاسیک — بنیادین و پایدار'), ('onyx', 'Onyx — تیره پرمیوم'), ('linen', 'Linen — روشن مینیمال'), ('clay', 'Clay — خمیری نرم'), ('atomic', 'Atomic — خطی تیز'), ('fluen', 'Fluen — فلویید'), ('glassmo', 'Glassmo — شیشه\u200cای'), ('md3', 'Material 3'), ('minimal', 'Minimal — تک\u200cرنگ'), ('neu', 'Neu — نئومورف'), ('skuermo', 'Skuerdo — رترو')], default='classic', help_text='نسخه\u200cی رابط کاربری ویجت؛ همه از یک تنظیمات شخصی\u200cسازی مشترک استفاده می\u200cکنند.', max_length=20),
        ),
    ]
