# Generated by Django 5.2.13 on 2026-09-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_alter_widgetconfig_widget_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('level', models.CharField(choices=[('off', 'خاموش'), ('simple', 'نگهبان ساده'), ('veteran', 'نگهبان کارکشته')], default='simple', max_length=10)),
                ('block_threshold', models.PositiveSmallIntegerField(default=3, help_text='بعد از چند تشخیص، کاربر بلاک شود (۲ تا ۲۰).')),
                ('block_message', models.TextField(default='به دلیل فعالیت مشکوک، دسترسی شما به چت مسدود شده است.', help_text='پیامی که به\u200cعنوان آخرین پاسخ برای کاربر بلاک\u200cشده نمایش داده می\u200cشود.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guard settings',
                'verbose_name_plural': 'Guard settings',
            },
        ),
    ]
