# Generated by Django 5.2.13 on 2026-09-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_guard_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='block_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='conversation',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
