# Generated by Django 5.2.13 on 2026-09-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_conversation_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='guard_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
