# Generated by Django 5.2.13 on 2026-09-11 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_conversation_guard_attempts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('business_type', models.CharField(choices=[('sales', 'فروش — متقاعدسازی حرفه\u200cای'), ('support', 'پشتیبانی — راهنمایی گام\u200cبه\u200cگام'), ('general', 'عمومی — پاسخ مستقیم به سؤالات')], default='general', max_length=10)),
                ('plan', models.CharField(choices=[('simple', 'ساده'), ('plus', 'پلاس'), ('pro', 'پرو')], default='simple', max_length=10)),
                ('message_limit', models.PositiveIntegerField(blank=True, help_text='سقف پیام در بازه (مرحله بعد فعال می\u200cشود).', null=True)),
                ('trial_days', models.PositiveSmallIntegerField(blank=True, help_text='بازه زمانی ۳۰/۹۰/۳۶۰ روز.', null=True)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site profile',
                'verbose_name_plural': 'Site profile',
            },
        ),
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_pages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_permissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
