# Generated by Django 5.2.13 on 2026-09-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_siteprofile_staffpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='message_limit',
        ),
        migrations.RemoveField(
            model_name='siteprofile',
            name='trial_days',
        ),
        migrations.AddField(
            model_name='message',
            name='units',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='period_months',
            field=models.PositiveSmallIntegerField(choices=[(1, '۱ ماهه'), (3, '۳ ماهه'), (12, '۱ ساله')], default=1),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='period_start',
            field=models.DateTimeField(blank=True, help_text='لنگرِ دوره\u200cهای ماهانه (تاریخ فعال\u200cسازی).', null=True),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='quota_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='suspended_origins',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='widgetconfig',
            name='input_size_class',
            field=models.CharField(choices=[('very_low', 'خیلی کم'), ('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('very_high', 'خیلی زیاد')], default='medium', help_text='چقدر ورودی یک پیام حساب شود (پشت\u200cصحنه).', max_length=12),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='plan',
            field=models.CharField(choices=[('simple', 'هم پاسخ'), ('plus', 'هم پاسخ پلاس'), ('pro', 'هم پاسخ پرو')], default='simple', max_length=10),
        ),
    ]
