"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APP_VERSION = "1.0.0"
IS_TESTING = any(arg == "test" or arg.startswith("test") for arg in sys.argv)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() in ("true", "1", "yes")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")
if not SECRET_KEY:
    if DEBUG or IS_TESTING:
        SECRET_KEY = (
            "django-insecure-dev-only-vp_haoh$2=d*ohzslo3-!byulo3ak0+cd12*@=a4=zp+@_hcn1"
        )
    else:
        from django.core.exceptions import ImproperlyConfigured

        raise ImproperlyConfigured(
            "SECRET_KEY is required in production. Generate one with "
            "`python -c \"import secrets; print(secrets.token_urlsafe(64))\"` "
            "and set it in the environment."
        )

ALLOWED_HOSTS = [
    h.strip()
    for h in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if h.strip()
]

# PaaS convenience: Railway injects RAILWAY_PUBLIC_DOMAIN (and its private
# networking domains). Adding them automatically removes the classic
# "DisallowedHost at /" first-deploy failure without weakening security —
# explicit ALLOWED_HOSTS entries still win and extra domains are append-only.
_RAILWAY_DOMAINS = [
    os.getenv(name, "").strip()
    for name in (
        "RAILWAY_PUBLIC_DOMAIN",
        "RAILWAY_STATIC_URL",
    )
]
_ALLOWED_EXTRA = [
    d
    for d in _RAILWAY_DOMAINS + [os.getenv("RAILWAY_PRIVATE_DOMAIN", "")]
    if d
]
for _domain in _ALLOWED_EXTRA:
    if _domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_domain)


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must run BEFORE corsheaders: corsheaders short-circuits CORS preflights
    # without calling get_response, so post-processing would never see them.
    'chat.middleware.PanelOriginCorsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'chat.middleware.SecurityHeadersMiddleware',
    'chat.middleware.AdminLoginRateLimitMiddleware',
    'chat.middleware.ApiRequestSizeLimitMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'chat.middleware.PlanEnforcementMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'chat.middleware.MediaDocumentProtectionMiddleware',
]

# The customizer's live preview embeds /panel/preview/ in a same-origin
# iframe; Django's default X-Frame-Options: DENY would kill it.
X_FRAME_OPTIONS = "SAMEORIGIN"

# Panel is the only visible control room; the admin site's login URL is
# still needed for redirects. LOGIN_URL must remain resolvable even though
# the sidebar no longer links to /admin/.
LOGIN_URL = "/admin/login/"

ROOT_URLCONF = 'config.urls'

DEFAULT_CHARSET = 'utf-8'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'chat.context_processors.panel_extras',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

def _database_url_options(url):
    """Parse DATABASE_URL (Railway-style) without extra dependencies.

    Accepts postgres://, postgresql:// and sqlite:// schemes and returns a
    Django DATABASES entry. Keeps deployment to one variable.
    """
    from urllib.parse import unquote, urlsplit

    parts = urlsplit(url)
    scheme = (parts.scheme or "").lower()
    if scheme in ("sqlite",):
        path = unquote(parts.path.lstrip("/")) or "db.sqlite3"
        if not os.path.isabs(path):
            path = str(BASE_DIR / path)
        return {"ENGINE": "django.db.backends.sqlite3", "NAME": path}
    if scheme in ("postgres", "postgresql"):
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parts.path.lstrip("/")),
            "USER": unquote(parts.username or ""),
            "PASSWORD": unquote(parts.password or ""),
            "HOST": parts.hostname or "",
            "PORT": str(parts.port or "5432"),
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
            "OPTIONS": {"connect_timeout": 5},
        }
    raise ImproperlyConfigured(
        f"Unsupported DATABASE_URL scheme: {scheme!r} (use postgres:// or sqlite://)"
    )


from django.core.exceptions import ImproperlyConfigured  # noqa: E402

_DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if _DATABASE_URL:
    DATABASES = {"default": _database_url_options(_DATABASE_URL)}
elif os.getenv("DB_NAME"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER", ""),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "127.0.0.1"),
            "PORT": os.getenv("DB_PORT", "5432"),
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
            "OPTIONS": {"connect_timeout": 5},
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# PaaS persistence: point media + RAG corpus at a mounted volume when
# provided. DATA_DIR is the canonical override for the RAG corpus;
# PERSIST_DIR sets both media and Data at once (one Railway volume).
_PERSIST_DIR = os.getenv("PERSIST_DIR", "").strip()
_DATA_DIR_ENV = os.getenv("DATA_DIR", "").strip()
if _DATA_DIR_ENV:
    _CORPUS_DATA_DIR = Path(_DATA_DIR_ENV)
elif _PERSIST_DIR:
    _CORPUS_DATA_DIR = Path(_PERSIST_DIR) / "Data"
else:
    _CORPUS_DATA_DIR = BASE_DIR / "Data"

if _PERSIST_DIR:
    MEDIA_ROOT = Path(_PERSIST_DIR) / "media"
else:
    MEDIA_ROOT = BASE_DIR / 'media'

# Single source of truth for the RAG corpus location (chunks.json,
# metadata.json, embeddings.npy). Everything reads this; nothing else
# derives its own path.
CORPUS_DATA_DIR = _CORPUS_DATA_DIR

MEDIA_URL = '/media/'
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024

# ─── Static serving in PaaS / single-container mode ───────────────────────
# Whitenoise serves STATIC_ROOT directly from Django so the widget JS, panel
# CSS and demo page work with zero reverse-proxy configuration. Enabled via
# USE_WHITENOISE=True (set in the container image); local dev stays untouched.
# NOTE: non-manifest storage on purpose — hashed filenames would break the
# customer install snippets that reference /static/widget/widget-<theme>.js.
if os.getenv("USE_WHITENOISE", "").lower() in ("true", "1", "yes"):
    MIDDLEWARE.insert(
        MIDDLEWARE.index("django.middleware.security.SecurityMiddleware") + 1,
        "whitenoise.middleware.WhiteNoiseMiddleware",
    )
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }


# ─── Cache — Redis in production, LocMem in dev ──────────────────────────
# Redis is required for cross-worker rate limiting and answer caching.
# In development (or when REDIS_URL is not set), LocMem works fine.
REDIS_URL = os.getenv("REDIS_URL", "")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
            "KEY_PREFIX": "aisup",
            "TIMEOUT": int(os.getenv("CACHE_TIMEOUT", "300")),
            "OPTIONS": {
                "ignore_exc": True,
            },
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": os.getenv("CACHE_LOCATION", "ai-support-cache"),
            "TIMEOUT": int(os.getenv("CACHE_TIMEOUT", "300")),
            "OPTIONS": {
                "ignore_exc": True,
            },
        }
    }


JAZZMIN_SETTINGS = {
    'site_title': 'AI Support Admin',
    'site_header': 'AI Support',
    'site_brand': 'AI Support',
    'welcome_sign': 'مرکز مدیریت و پایش دستیار هوشمند',
    'copyright': 'AI Support',
    'show_ui_builder': False,
    'navigation_expanded': True,
    'custom_css': 'admin/css/support_admin.css',
    'icons': {
        'chat.widgetconfig': 'fas fa-sliders-h',
        'chat.document': 'fas fa-file-lines',
        'chat.analyticsevent': 'fas fa-chart-line',
        'chat.adminnotification': 'fas fa-bell',
    },
}

# CORS — required when the widget is embedded on external sites
CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
    if origin.strip()
]
CORS_ALLOW_ALL_ORIGINS = os.getenv(
    'CORS_ALLOW_ALL_ORIGINS',
    'True' if DEBUG else 'False',
).lower() in ('true', '1', 'yes')
CORS_ALLOW_HEADERS = [
    'content-type',
    'authorization',
    'x-csrftoken',
    'x-widget-key',
]
CORS_URLS_REGEX = r'^/api/.*$'

WIDGET_PUBLIC_KEY = os.getenv("WIDGET_PUBLIC_KEY", "").strip()
WIDGET_REQUIRE_KEY = os.getenv(
    "WIDGET_REQUIRE_KEY",
    "False" if DEBUG or IS_TESTING else "True",
).lower() in ("true", "1", "yes")
WIDGET_ALLOWED_ORIGINS = tuple(
    origin.strip().rstrip("/")
    for origin in os.getenv(
        "WIDGET_ALLOWED_ORIGINS",
        os.getenv("CORS_ALLOWED_ORIGINS", ""),
    ).split(",")
    if origin.strip()
)
WIDGET_RATE = os.getenv("WIDGET_RATE", "30/minute")
WIDGET_EVENTS_RATE = os.getenv("WIDGET_EVENTS_RATE", "120/minute")
WIDGET_KEY_RATE = os.getenv("WIDGET_KEY_RATE", "1000/minute")
WIDGET_FEEDBACK_RATE = os.getenv("WIDGET_FEEDBACK_RATE", "60/minute")
WIDGET_LEADS_RATE = os.getenv("WIDGET_LEADS_RATE", "10/minute")
WIDGET_HANDOFF_RATE = os.getenv("WIDGET_HANDOFF_RATE", "10/minute")
RAG_MAX_CONCURRENT = int(os.getenv("RAG_MAX_CONCURRENT", "8"))
RAG_RESPONSE_CACHE_SECONDS = int(
    os.getenv("RAG_RESPONSE_CACHE_SECONDS", "60")
)
TRUST_X_FORWARDED_FOR = os.getenv(
    "TRUST_X_FORWARDED_FOR", "False",
).lower() in ("true", "1", "yes")

# PaaS proxies (Railway included) terminate TLS and forward X-Forwarded-Proto.
# Default ON when not DEBUG so HTTPS detection works without manual env setup;
# explicit TRUST_PROXY_SSL still overrides both ways.
if os.getenv("TRUST_PROXY_SSL") is None and not DEBUG:
    TRUST_PROXY_SSL = True
else:
    TRUST_PROXY_SSL = os.getenv(
        "TRUST_PROXY_SSL", "False",
    ).lower() in ("true", "1", "yes")

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": (
        "rest_framework.renderers.JSONRenderer",
    ),
    "DEFAULT_PARSER_CLASSES": (
        "rest_framework.parsers.JSONParser",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "widget": WIDGET_RATE,
        "widget_events": WIDGET_EVENTS_RATE,
        "widget_key": WIDGET_KEY_RATE,
        "widget_feedback": WIDGET_FEEDBACK_RATE,
        "widget_leads": WIDGET_LEADS_RATE,
        "widget_handoff": WIDGET_HANDOFF_RATE,
    },
    "UNAUTHENTICATED_USER": None,
}

SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https")
    if TRUST_PROXY_SSL
    else None
)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_CONTENT_TYPE_NOSNIFF = not DEBUG
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_SSL_REDIRECT = os.getenv("SECURE_SSL_REDIRECT", "False").lower() in (
    "true", "1", "yes",
)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "0"))

# CSRF behind a proxy: Django 4+ requires the caller origin to be listed.
# Railway domain (if any) is trusted automatically; extra origins via env.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
for _domain in _ALLOWED_EXTRA:
    _origin = f"https://{_domain}"
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)


# Email
MAILERS = {
    "default": {
        "BACKEND": os.getenv(
            "MAIL_BACKEND",
            "django.core.mail.backends.console.EmailBackend"
            if DEBUG
            else "django.core.mail.backends.smtp.EmailBackend",
        ),
        "OPTIONS": {
            "host": os.getenv("MAIL_HOST", "localhost"),
            "port": int(os.getenv("MAIL_PORT", "25")),
            "username": os.getenv("MAIL_USER", ""),
            "password": os.getenv("MAIL_PASSWORD", ""),
            "use_tls": os.getenv("MAIL_USE_TLS", "False").lower()
            in ("true", "1", "yes"),
            "timeout": int(os.getenv("MAIL_TIMEOUT", "10")),
        },
    },
}

# ─── Monitoring ──────────────────────────────────────────────────────────
# Error rate threshold (errors per minute) that triggers a notification.
MONITORING_ERROR_THRESHOLD = int(os.getenv("MONITORING_ERROR_THRESHOLD", "10"))
# Request latency threshold (ms) that triggers a pressure notification.
MONITORING_LATENCY_THRESHOLD_MS = int(
    os.getenv("MONITORING_LATENCY_THRESHOLD_MS", "5000")
)
